### ISSUE TITLE
mission pickup warning

### ISSUE THREAD

**Issue by TwiZted6** [CMDR-WDX/EDMC-Massacres#21] opened 2023-05-04 04:09 UTC
so everything works fine except the warning for when youv picked up more than 1 mission from the same person has stopped working

**Comment by CMDR-WDX** [comment] 2023-05-04 20:44
Hey. Thanks for the Issue. 
I don't have Elite installed atm so I have to ask you for some logs. If you look at `%TEMP%/EDMarketConnector` you should find a folder with log files. Could you send me the most recent log? If the Plugin failed somewhere, that log should contain stack traces that could point to the reason. 

Can I also ask what type of Massacre missions we are talking about? Was it two Pirate Targets? Was is a Pirate and, e.g. a Civilian Target?

**Comment by CMDR-WDX** [comment] 2023-08-21 16:59
I will be closing this issue as I could not reproduce and there has not been any new info provided. 

Feel free to reopen or comment if you (or any other user) faces this issue :)

**Closed as not planned by CMDR-WDX** 2023-08-21 16:59 UTC
Labels: bug, more info needed
